// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Module4HW6.DataAccess;

namespace Module4HW6.DataAccess.Migrations
{
    [DbContext(typeof(BankContext))]
    [Migration("20211121153639_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Module4HW6.DataAccess.DbModels.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ArtistId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("DateOfBirth");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .HasColumnName("Email");

                    b.Property<string>("InstagramUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("InstagramUrl");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("Phone");

                    b.HasKey("Id");

                    b.ToTable("Artist");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1980, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "artist1@outlook.com",
                            InstagramUrl = "https://www.instagram.com/artist1",
                            Name = "Artist 1",
                            Phone = "380961234567"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1990, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "artist2@outlook.com",
                            InstagramUrl = "https://www.instagram.com/artist2",
                            Name = "Artist 2",
                            Phone = "380661234567"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "artist3@outlook.com",
                            InstagramUrl = "https://www.instagram.com/artist3",
                            Name = "Artist 3",
                            Phone = "380963456789"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(1977, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "artist4@outlook.com",
                            InstagramUrl = "https://www.instagram.com/artist4",
                            Name = "Artist 4",
                            Phone = "380663456789"
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(1995, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "artist5@outlook.com",
                            InstagramUrl = "https://www.instagram.com/artist5",
                            Name = "Artist 5",
                            Phone = "380555555555"
                        });
                });

            modelBuilder.Entity("Module4HW6.DataAccess.DbModels.ArtistSong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ArtistSongId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("SongId");

                    b.ToTable("ArtistSong");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtistId = 1,
                            SongId = 1
                        },
                        new
                        {
                            Id = 2,
                            ArtistId = 2,
                            SongId = 2
                        },
                        new
                        {
                            Id = 3,
                            ArtistId = 3,
                            SongId = 3
                        },
                        new
                        {
                            Id = 4,
                            ArtistId = 4,
                            SongId = 4
                        },
                        new
                        {
                            Id = 5,
                            ArtistId = 5,
                            SongId = 5
                        },
                        new
                        {
                            Id = 6,
                            ArtistId = 1,
                            SongId = 6
                        },
                        new
                        {
                            Id = 7,
                            ArtistId = 2,
                            SongId = 7
                        },
                        new
                        {
                            Id = 8,
                            ArtistId = 3,
                            SongId = 8
                        },
                        new
                        {
                            Id = 9,
                            ArtistId = 4,
                            SongId = 9
                        },
                        new
                        {
                            Id = 10,
                            ArtistId = 5,
                            SongId = 10
                        },
                        new
                        {
                            Id = 11,
                            ArtistId = 5,
                            SongId = 1
                        },
                        new
                        {
                            Id = 12,
                            ArtistId = 4,
                            SongId = 1
                        },
                        new
                        {
                            Id = 13,
                            ArtistId = 3,
                            SongId = 2
                        },
                        new
                        {
                            Id = 14,
                            ArtistId = 2,
                            SongId = 3
                        },
                        new
                        {
                            Id = 15,
                            ArtistId = 1,
                            SongId = 4
                        },
                        new
                        {
                            Id = 16,
                            ArtistId = 1,
                            SongId = 3
                        },
                        new
                        {
                            Id = 17,
                            ArtistId = 2,
                            SongId = 4
                        },
                        new
                        {
                            Id = 18,
                            ArtistId = 3,
                            SongId = 4
                        },
                        new
                        {
                            Id = 19,
                            ArtistId = 4,
                            SongId = 10
                        },
                        new
                        {
                            Id = 20,
                            ArtistId = 5,
                            SongId = 8
                        });
                });

            modelBuilder.Entity("Module4HW6.DataAccess.DbModels.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GenreId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.ToTable("Genre");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Genre 1"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Genre 2"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Genre 3"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Genre 4"
                        },
                        new
                        {
                            Id = 5,
                            Title = "Genre 5"
                        });
                });

            modelBuilder.Entity("Module4HW6.DataAccess.DbModels.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SongId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("Duration");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleasedDate")
                        .HasColumnType("date")
                        .HasColumnName("ReleasedDate");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Song");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Duration = 180,
                            GenreId = 1,
                            ReleasedDate = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Song 1"
                        },
                        new
                        {
                            Id = 2,
                            Duration = 190,
                            GenreId = 2,
                            ReleasedDate = new DateTime(2015, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Song 2"
                        },
                        new
                        {
                            Id = 3,
                            Duration = 200,
                            GenreId = 3,
                            ReleasedDate = new DateTime(2015, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Song 3"
                        },
                        new
                        {
                            Id = 4,
                            Duration = 210,
                            GenreId = 4,
                            ReleasedDate = new DateTime(2015, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Song 4"
                        },
                        new
                        {
                            Id = 5,
                            Duration = 220,
                            GenreId = 5,
                            ReleasedDate = new DateTime(2015, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Song 5"
                        },
                        new
                        {
                            Id = 6,
                            Duration = 230,
                            GenreId = 1,
                            ReleasedDate = new DateTime(2015, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Song 6"
                        },
                        new
                        {
                            Id = 7,
                            Duration = 240,
                            GenreId = 1,
                            ReleasedDate = new DateTime(2015, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Song 7"
                        },
                        new
                        {
                            Id = 8,
                            Duration = 250,
                            GenreId = 2,
                            ReleasedDate = new DateTime(2015, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Song 8"
                        },
                        new
                        {
                            Id = 9,
                            Duration = 260,
                            GenreId = 3,
                            ReleasedDate = new DateTime(2015, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Song 9"
                        },
                        new
                        {
                            Id = 10,
                            Duration = 270,
                            GenreId = 0,
                            ReleasedDate = new DateTime(2015, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Song 10"
                        });
                });

            modelBuilder.Entity("Module4HW6.DataAccess.DbModels.ArtistSong", b =>
                {
                    b.HasOne("Module4HW6.DataAccess.DbModels.Artist", "Artist")
                        .WithMany("ArtistSongs")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Module4HW6.DataAccess.DbModels.Song", "Song")
                        .WithMany("ArtistSongs")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("Module4HW6.DataAccess.DbModels.Song", b =>
                {
                    b.HasOne("Module4HW6.DataAccess.DbModels.Genre", "Genre")
                        .WithMany("Songs")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Module4HW6.DataAccess.DbModels.Artist", b =>
                {
                    b.Navigation("ArtistSongs");
                });

            modelBuilder.Entity("Module4HW6.DataAccess.DbModels.Genre", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("Module4HW6.DataAccess.DbModels.Song", b =>
                {
                    b.Navigation("ArtistSongs");
                });
#pragma warning restore 612, 618
        }
    }
}
